repos:

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
        files: ^(src/|tests/|pyproject\.toml|requirements.*\.txt$)
        exclude: ^(docs/|README\.md$)